### ISSUE TITLE
`@defective="true"` should upwards inherit to parent msItem elements

### ISSUE THREAD

**Issue by wlpotter** [srophe/britishLibrary-data#1468]
In cases where we have a tei:msItem element that is a child of another tei:msItem (i.e., `./parent::msItem`) and the child element has `@defective="true"`, then this should also be added to the parent msItem if it is not already marked as defective.

The editorial reason is that the child item is considered a logical and physical part of the the parent item, so if it is defective than the containing parent is also defective.

**Comment by wlpotter** [comment]
I have a script ready to go to change data here: https://github.com/wlpotter/sandbox/blob/main/smbl_upwards-inherit-defective-status.xq

I am wondering if we will also want a schema or schematron rule that requires this? (e.g., if `.//msItem[@defective="true"` then require `@defective="true"` on the context item -- which would apply to all msItem elements). To discuss

**Comment by dlschwartz** [comment]
Fixed with commit above
