### ISSUE TITLE
Remove multiple tei:support instead use multiple tei:material inside single tei:support

### ISSUE THREAD

**Issue by dlschwartz** [srophe/britishLibrary-data#1507]
@davidamichelson this is the most complicated example from 1110.xml and before making changes I wanted to be sure I marked this up the way you want it.

### More complicated example
[Current markup in 1110.xml](https://github.com/srophe/britishLibrary-data/blob/schema-edits/data/tei/1110.xml#L133).

This proposed change matches Wright rather closely but I could easily imagine other punctuation:
```
<supportDesc material="mixed">
  <support>
    <material>Vellum</material>
    <material>Paper  (<locus from="1" to="2">foll. 1, 2</locus>, <locus from="71" to="89">71—89</locus>, <locus from="98" to="99">98, 99</locus>, <locus from="189" to="190">189, and 190</locus>)</material>
  </support>
</supportDesc>
```

### Less complicated examples
[Current markup in 745.xml](https://github.com/srophe/britishLibrary-data/blob/schema-edits/data/tei/745.xml#L126)

Change to:
```
<supportDesc material="perg">
  <support>
    <material>Vellum</material>
    <material>Paper (<locus from="147" to="148">147, 148</locus>)</material>
  </support>
</supportDesc>
```

**Comment by davidamichelson** [comment]
@dlschwartz can you write a script to make this change please?
