### ISSUE TITLE
Remove all desc from tei:handNote

### ISSUE THREAD

**Issue by dlschwartz** [srophe/britishLibrary-data#1508]
@davidamichelson, we decided to remove the tei:desc children of tei:handNote to allow tei:note elements. However, what would we do in the case of multiple tei:desc children of tei:handNote. See [530.xml](https://github.com/srophe/britishLibrary-data/blob/schema-edits/data/tei/530.xml#L178). This would be a reason to replace tei:desc with tei:p.

**Comment by davidamichelson** [comment]
@dlschwartz This is ready for you to do.
