### ISSUE TITLE
Write a script to insert persName in every msItem/author and clean up the data

### ISSUE THREAD

**Issue by davidamichelson** [srophe/britishLibrary-data#1510]
@wlpotter Can you assist with this and let's discuss.
1. Where will we put the @ref on author or persName or both?
2. How will we revert @type=uniform?
3. We need to be strict about only one conceptual person per Author element and use multple authors if needed.

**Comment by wlpotter** [comment]
I'm going to close this since discussed the three points and I have issue #477 for making this change already
