### ISSUE TITLE
Add @type="MS" to all TEI:bibl that contain TEI:ptr

### ISSUE THREAD

**Issue by davidamichelson** [srophe/britishLibrary-data#1513]
Should we do this?

**Comment by wlpotter** [comment]
Note that with #1553 we will have tei:ref not tei:ptr

**Comment by wlpotter** [comment]
I think we want to do this, and should do so before we change so they are tei:ref rather than tei:ptr (although we can always check that the target attribute includes a manuscript URI and apply the type that way)

**Comment by wlpotter** [comment]
Fixed
