### ISSUE TITLE
Warning messages on msPart regarding material and physical form

### ISSUE THREAD

**Issue by dlschwartz** [srophe/britishLibrary-data#1522]
Search "<msPart" at XPath `msPart[msPart]`.
- There you will find all of the warning messages on msPart about material and about physical form [files 61, 106, 222, 629, 693, 739, 811, 856].
- You will also find two records that do not throw this error message [496 and 872].

The reason for this difference is the XPath. The rule expects to find `msPart/child::physDesc`. 
- Where the rule fires we have `msPart[not(physDesc)]/msPart/physDesc`. The rule fires on the first msPart but not the second.
- Where the rule doesn't fire, we have `msPart[msPart/physDesc]/physDesc`. In other words the msPart that contains another msPart has its own physDesc and the msPart that is contained by the first also has a physDesc. This seems (potentially but not necessarily?) a bit redundant, but validates.

Options:
1. This is a warning, not an error. We can ignore it.
2. I can write a new rule that validates with `msPart/descendant::physDesc` and we can document the difference.
3. We can look at the data and see if we can add a physDesc to the first msPart.

We should certainly start with option 3. We already do this in records 496 and 872, and whenever possible it's preferable to conform to the BL schema.  We can consider the other options if this doesn't work.

**Comment by davidamichelson** [comment]
Discuss on Friday with @wlpotter

**Comment by davidamichelson** [comment]
We will review and add these.

**Comment by davidamichelson** [comment]
Copy the attribute data upward and a p in physdesc explaining
