### ISSUE TITLE
Keep tei:bibl/@xml:id

### ISSUE THREAD

**Issue by davidamichelson** [srophe/britishLibrary-data#1528]
@wlpotter Should we just ditch this usage? What does it even refer to? The Word documents?

```
<additional>
              <adminInfo>
                <recordHist>
                  <source>Manuscript description based on <bibl>
                      <ref target="#Wrightpart27">Wright's
                            Catalogue</ref>
                    </bibl>, abbreviated by the Syriaca.org editors.</source>
                </recordHist>
                </adminInfo>
              <listBibl>
                <bibl xml:id="Wrightpart27">
                  <author>William Wright</author>
                  <title xml:lang="en">Catalogue of Syriac Manuscripts in the British Museum Acquired
                        since the Year 1838</title>
                  <pubPlace>London</pubPlace>
                  <date>1870</date>
                  <ptr target="http://syriaca.org/bibl/8"/>
                  <citedRange unit="entry">MXII</citedRange>
                  <citedRange unit="p">3:1195</citedRange>
                <ref type="internet-archive-pdf" target="https://archive.org/details/catalogueofsyria03brituoft/page/1195"/>
                </bibl>
              </listBibl>
            </additional>
```

**Comment by wlpotter** [comment]
I think we want to keep this functionality? We do want to retain the listBibl/bibl for Wright's entry (especially if we harvest this for the union catalogue, we will want to retain the reference to the catalogue). The link between recordHist and the bibl xml:id is important for tracking the provenance of the TEI record so we can say that we got our data from Wright, and then any recordHist/change elements can record major divergences we make from Wright (i.e., re-dividing the entries, etc.).

We could include the full bibl reference inside recordHist/source instead, but this might lead to reduplication with the listBibl anyway? I wonder though if we want to use a `@corresp` on the source/bibl to point to the xml:id instead, as this more clearly links the two?

**Comment by davidamichelson** [comment]
Okay keep this.

**Comment by davidamichelson** [comment]
Require this when in addition, optional elsewhere
