### ISSUE TITLE
Add Dan as Technical Editor for every record

### ISSUE THREAD

**Issue by davidamichelson** [srophe/britishLibrary-data#1530]
@wlpotter if you concur?

**Comment by wlpotter** [comment]
Yes, please do add Dan as technical editor!

**Comment by davidamichelson** [comment]
Add Will and me too? Also review header in general

**Comment by davidamichelson** [comment]
Add Will as general editor

**Comment by wlpotter** [comment]
@davidamichelson I wonder if we want to implement this when we make overall changes to the titleStmt, seriesStmt, etc.? To keep in line with other Srophe apps we would want general and technical editors to be declared at the SeriesStmt, not at the titleStmt level

**Comment by wlpotter** [comment]
Fixed
