### ISSUE TITLE
Should #sci-logic be in keywords/@scheme?

### ISSUE THREAD

**Issue by davidamichelson** [srophe/britishLibrary-data#1531]
We only have two values in it:  #sci-logic #Wright-BL-Taxonomy

**Comment by davidamichelson** [comment]
Nevermind

**Comment by wlpotter** [comment]
Yes, if and when we remove the textClass section for Wright's classification (b/c we've moved it to the tei:head element for each desc or part), then this should be fixed

**Comment by davidamichelson** [comment]
We may get rid of all of this. Wait until Will updates the tei:head to see if we still need it.

#sci-logic is a mistake, will edit  out.
