### ISSUE TITLE
Add to documentation that we use persName for groups

### ISSUE THREAD

**Issue by davidamichelson** [srophe/britishLibrary-data#1533]
We do have one instance in which it points to ref="http://syriaca.org/person/1606" The Apostles

**Comment by dlschwartz** [comment]
FWIW, I would argue that "the Apostles" is a person group and not an organization.

**Comment by davidamichelson** [comment]
convert all orgName to persName (and in the Person URIs we indicate groups)

**Comment by davidamichelson** [comment]
Add to documentation

**Comment by davidamichelson** [comment]
Closed with https://github.com/srophe/britishLibrary-data/commit/adf608fc56e59737ff0e1fc74e8c412890bc499d

**Comment by davidamichelson** [comment]
Reopening as add to documentation
