### ISSUE TITLE
Update langUsage across all records using the finalized list of language codes and their labels

### ISSUE THREAD

**Issue by wlpotter** [srophe/britishLibrary-data#1542]
#26 has the list of all language tags, and the list of labels for these language codes is in [this issue](https://github.com/srophe/britishLibrary/issues/310).

Update all records' tei:langUsage nodes with this list. Add "und" for Undetermined to that list

We will then want to constrain the values of xml:lang to that list

**Comment by wlpotter** [comment]
Data is updated here @dlschwartz, so the schema can constrain the values of `@xml:lang` and `@script` based on what appears in the `/TEI/teiHeader/profileDesc/langUsage/language/@ident` list

**Comment by dlschwartz** [comment]
@wlpotter Commit linked above address this schema change. Please test and close.

**Comment by wlpotter** [comment]
I think it's missing xml:lang on tei:quote? From tests the error fires on title and rubric and finalRubric, and I believe note as well. But when I change the xml:lang on quote it doesn't throw an error

**Comment by dlschwartz** [comment]
Do we require xml:lang on quote or is it optional?

**Comment by dlschwartz** [comment]
Fixed with https://github.com/srophe/britishLibrary/commit/574593f38b7b83a6928197afb3fddfdd3ee36e3e
