### ISSUE TITLE
@xml:lang="en" on msItem/title

### ISSUE THREAD

**Issue by davidamichelson** [srophe/britishLibrary-data#1551]
We have msItem/title/@xml:lang="en" in 10,657 cases and have no xml:lang value in 4797 cases (most of which do seem to be english but some might be latin etc.)

Should we normalize this? We could just remove "en" and say that it is inherited from the main lang?

**Comment by dlschwartz** [comment]
I think we have titles in Latin and Syriac. I think we want to keep this attribute

**Comment by davidamichelson** [comment]
@dlschwartz Okay, could you please add xml:lang="en" to all //msItem/title[not(@xml:lang)] and then require that all //msItem/title have an xml:lang value?
