### ISSUE TITLE
ISO Codes

### ISSUE THREAD

**Issue by davidamichelson** [srophe/britishLibrary-data#1568]
We should confirm if we have actually done this:
We have conformed to the BCP 47 standard (http://www.rfc-editor.org/rfc/bcp/bcp47.txt) which recommends using the two letter language code when available from [ISO 639-1](https://www.loc.gov/standards/iso639-2/php/code_list.php/) codes and then using three letter language codes from [ISO 639-3](http://www-01.sil.org/iso639-3/codes.asp) only for languages not included in ISO 639-1, then an [ISO 15924](https://www.unicode.org/iso15924/)code for the script, and finally [IANA language subtags](https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry) for other information, such as methods of transliteration.

**Comment by wlpotter** [comment]
Yes we do follow this -- though we do not use IANA language subtags since we don't provide things like methods of transliteration in SMBL
