### ISSUE TITLE
Add. 14,591 | https://bl.syriac.uk/ms/327 test

### ISSUE THREAD

**Issue by andrewtucker1** [srophe/britishLibrary-data#1578]
test issue (this is my second attempt, I didn't assign it the first time).

am I also linking this correctly? Let me know if I'm missing something!
https://github.com/srophe/britishLibrary-data/blob/e50493f976bccafacf11f8d732c37118f5a5d938/data/tei/318.xml#L268

**Comment by wlpotter** [comment]
Thanks, closing test issue!

Also, fyi you can assign issues even after they are opened in the panel to the right
