### ISSUE TITLE
Add. 14,677 | https://bl.syriac.uk/ms/533 A note that is in fact a footnote to Syriac word in Wright - it does not make sense on its own - what to do?

### ISSUE THREAD

**Issue by SPuchkova** [srophe/britishLibrary-data#1579]
https://github.com/srophe/britishLibrary-data/blob/e50493f976bccafacf11f8d732c37118f5a5d938/data/tei/533.xml#L116

**Comment by wlpotter** [comment]
Thanks @SPuchkova ! I think we maybe looked at this one on Wednesday? Here we would give this note a `@type` attribute with the value "footnote": `<note type="footnote">I.e., the two songs of <persName>Moses</persName> and the song of...</note>`.

You can then move the note up to match where Wright has the footnote. I believe in this case this was in the Syriac rubric or final rubric?

**Comment by SPuchkova** [comment]
Done!
