### ISSUE TITLE
Add. 14,675 | https://bl.syriac.uk/ms/529 Review Gomiero

### ISSUE THREAD

**Issue by GiovanniGomiero** [srophe/britishLibrary-data#1587]
https://bl.syriac.uk/ms/529 ms. Add. 14675

**Comment by wlpotter** [comment]
Hi @GiovanniGomiero were there specific questions on this manuscript? (or maybe this was the test issue?)

**Comment by GiovanniGomiero** [comment]
Only the test issue! Now the manuscript is marked as _done_ in the excel!

**Comment by wlpotter** [comment]
Wonderful, thank you! I didn't want to close it without confirming
