### ISSUE TITLE
Add. 14,677 | https://bl.syriac.uk/ms/533 The weird Website presentation of the diacritics

### ISSUE THREAD

**Issue by SPuchkova** [srophe/britishLibrary-data#1608]
Just to let you know, the website displays weirdly the lines above the words in Syriac that Wright has in his catalog. It is pretty tolerable in Oxygen, though.

**Comment by SPuchkova** [comment]
Permalink is here: https://github.com/srophe/britishLibrary-data/blob/7ed9d834c099761265cdcb643468a8d01e06be53/data/tei/533.xml#L108

**Comment by wlpotter** [comment]
Thanks @SPuchkova, I believe this is abbreviation mark character? Unfortunately, this is a known issue with the Syriac fonts themselves. If it looks correct in the XML file, then that is fine

**Comment by SPuchkova** [comment]
Thanks, Will! Yes, we discussed it. I put it here just for your records.
