### ISSUE TITLE
Add. 18,716, foll. 2–57 | https://bl.syriac.uk/ms/1474 Arabic should be checked

### ISSUE THREAD

**Issue by SPuchkova** [srophe/britishLibrary-data#1609]
I'm not competent in Arabic, so it should be checked by another person.

**Comment by SPuchkova** [comment]
Can't provide permalink since the page doesn't exist
https://github.com/srophe/britishLibrary-data/blob/main/data/tei/1473.xml

**Comment by wlpotter** [comment]
Thanks @SPuchkova! We will have someone check the Arabic.

As an aside, unfortunately, the permalink to GitHub only works at the file-level, so for multi-part manuscripts this would have to be https://github.com/srophe/britishLibrary-data/blob/main/data/tei/1117.xml

**Comment by wlpotter** [comment]
Reopening to remind us to add the Arabic

**Comment by Erfan-Syriaca** [comment]
proofread.
