### ISSUE TITLE
{BL 17,134} | {https://bl.syriac.uk/ms/763} Problem with Syriac in website due to lines 

### ISSUE THREAD

**Issue by YaelNueKr** [srophe/britishLibrary-data#1611]
### Problems with Manuscript Contents

See note added on xml under msContents and in the website https://bl.syriac.uk/ms/763

**Comment by YaelNueKr** [comment]
The reasons for supposing that this manuscript is an autograph of the famous Jacob, bishop of Edessa, are— 1. The antiquity of the volume. 2. The character of the handwriting, which is not regular enough for that of a professional scribe. 3. The absence of any indication of another scribe. 4. The care with which the specifications contained in the note,fol. 75 a, have been adhered to throughout the whole volume, thus giving it an entirely different character and appearance from those of such copies as Add. 18,816. Hymn 271 (ܪܥܐ), fol. 61 b, may serve as an example, a line marking the words and letters which are written with red paint. The title, as far as ܘܠܠܝܐ, is yellow.ܐܚܪܬܐ ܥܠ ܕܝܪ̈ܝܐ ܟܕ ܦܢ̣ܐ ܡܢ ܣܥܘܪܘܬܐ ܕܕܝܪ̈ܬܐ. ܗ̈ܘܝ ܕܡ̈ܥܝ ܠܝ ܠܚ̣̇ܡܐ ܐܝܡܡܐ ܘܠܠܝܐ. ܐܡܬܝ(ܕܐܣ̇ܒ) ܕܢ̇ܣܒ ܐܢܐ ܒܗܘܢܐ: ܠܗ̇ܢܘܢ ܕܕܘܒܪܐ (ܕܝܪܝܐ) ܢܙܝܪܐ ܡܬܥ̇ܢܘܝܢ (ܘܡܟܪܟܝܢ ܒܦܓܪܐ) ܘܫܩ̣ܝܠܝܢ ܒܦܓܪ̈ܝܗܘܢ ܠܡܝܬܘܬܐ ܡܥ̣ܒܕܬ݁ ܚ̈ܝܐ ܕܝܫܘܥ ܐ܏ܠܗܐ ܡ܏ܠܬܐ ܏ܕܐ̇ܬܒܣܪ: ܘܒܐܝܡܡܐ ܘܠܠܝܐ. ܡܬ݁ܗܓܝܢ ܏ܐܡ̣ܝܢܐܝܬ ܘ܏ܥ̇ܢ̣ܝܢ ܒܢܡܘܣܗ ܕܡܪܝܐ: ܘܡ̇ܒ̣ܥܝܢ ܏ܐܝܟ ܏ܡ̈ܥܝܢܐ ܏ܠܬܫ̈ܒܚܬܐ ܘ̄ܕ̈ܘܡܪܐ ܚ̈ܠܝܐ ܕܐܠܗܐ (ܒܓܓܪܬܗܘܢ) ܒܓܓܪ̈ܬܗܘܢ: ܐ̇ܠܐ ܐ̣ܢܐ ܠܚ̈ܝ ܕ܏ܘ̈ܝܐ܇ (ܟܕ) ܕܚ̇ܙܐ ܐܢܐ ܕܐܥ̣ܬܩܘ ܏ܘܓܡ̣ܪܘ ܒܥ̈ܡܠܐ ܣܪ̈ܝܩܐ ܕ܏ܠܐ ܝ܏ܘܬܪܢ. ܘܥܡ ܏ܚ̣ܫܐ (ܕܘ̈ܘܢܐ) ܘ̄ܟܐܒܐ ܕܠ܏ܒܐ ܡ̇ܙܥ̣ܩ ܐ̣ܢܐ̣. ܕ̄ܡ̣ܢܘ ܢܬ݁ܠ ܠܪܝܫ ܡ̈ܝܐ܇ ܐܦ ܡܒܘܥܐ ܫ܏ܦ̣ܝܥܐ ܕܡ̈ܥܐ ܠܥܝ̈ܢܐ ܕܝܠܝ. ܐܝܟܢܐ ܕܟܕ ܏ܒܡܪܓܫܢܘܬܐ ܏ܐܘܟܝܬ ܝܕܥܬܐ ܕܒܝ̈ܫܬܝ ܏ܗ̇ܘܐ ܐ̣܏ܢܐ ܐܪܟ̇ܢ ܏ܠܘܬܝ ܗ̇ܘ ܣܓܝܐܐ ܒܪ̈ܚܡܐ ܠܡܫܝܚܐ ܣ̇ܓܝ ܪ̈ܚܡܐ ܘ̄ܐܫ̣ܬܘܐ ܠܚܘ̈ܣܢܘܗܝ ܣ̈ܓܝܐܐ. 5. The transcription in full, on the upper and lower margins, of all the passages of Scripture referred to in the hymns. 6. The general accuracy with which the Greek proper names and other words are written in Greek letters; and the correctness with which they are represented in Syriac characters. Such mistakes as ΤΙΒΕΡΙΟⲤ, ܒܝܡܐ ܕܛܝܒܐܪܝܘܣ (fol. 19 a), are rare.


here is what i was referring to

**Comment by wlpotter** [comment]
Yes, @YaelNueKr this is similar to #1635 where the Syriac text appears in an English-language note. You can need to tag the Syriac as quote element: `<quote xml:lang="syr"></quote>`. The `@xml:lang` will tell the app that it is Syriac, and so should help with displaying it properly
