### ISSUE TITLE
{17,134} | {https://bl.syriac.uk/ms/763} order of english in website unsuitable with xml

### ISSUE THREAD

**Issue by YaelNueKr** [srophe/britishLibrary-data#1612]
### Problems with Manuscript Contents

Item 89 (Fol. 26a): [John bar Aphtūnāyā](https://bl.syriac.uk/search.html?author=http://syriaca.org/person/52). Fourth hymn
should be opposite (fourth hymn. John bar Aphtunaya). This is how it is in the xml. unsure of what to do

**Comment by wlpotter** [comment]
Thanks @YaelNueKr ! In general we would want the author element to come before the title element, so you could reorder these in the XML
