### ISSUE TITLE
Add. 14,719 | https://bl.syriac.uk/ms/599 Attribute "supplied" needed for several titles "Canticle" not found in Wright (line numbers in description)

### ISSUE THREAD

**Issue by ahannoush** [srophe/britishLibrary-data#1624]
https://github.com/srophe/britishLibrary-data/blob/7ed9d834c099761265cdcb643468a8d01e06be53/data/tei/599.xml#L140

https://github.com/srophe/britishLibrary-data/blob/7ed9d834c099761265cdcb643468a8d01e06be53/data/tei/599.xml#L154

https://github.com/srophe/britishLibrary-data/blob/7ed9d834c099761265cdcb643468a8d01e06be53/data/tei/599.xml#L159

https://github.com/srophe/britishLibrary-data/blob/7ed9d834c099761265cdcb643468a8d01e06be53/data/tei/599.xml#L164

https://github.com/srophe/britishLibrary-data/blob/7ed9d834c099761265cdcb643468a8d01e06be53/data/tei/599.xml#L169

https://github.com/srophe/britishLibrary-data/blob/7ed9d834c099761265cdcb643468a8d01e06be53/data/tei/599.xml#L174

https://github.com/srophe/britishLibrary-data/blob/7ed9d834c099761265cdcb643468a8d01e06be53/data/tei/599.xml#L179

https://github.com/srophe/britishLibrary-data/blob/7ed9d834c099761265cdcb643468a8d01e06be53/data/tei/599.xml#L195

https://github.com/srophe/britishLibrary-data/blob/7ed9d834c099761265cdcb643468a8d01e06be53/data/tei/599.xml#L200

**Comment by davidamichelson** [comment]
Thank you!
