### ISSUE TITLE
Add. 14,719 | https://bl.syriac.uk/ms/599 Does "a priest whose name has been erased" need to be added to new Syriaca person records?

### ISSUE THREAD

**Issue by ahannoush** [srophe/britishLibrary-data#1627]
https://github.com/srophe/britishLibrary-data/blob/7ed9d834c099761265cdcb643468a8d01e06be53/data/tei/599.xml#L308

**Comment by wlpotter** [comment]
No need to create a record on the spreadsheet for this person; and please also remove the `<persName>` tags for the unidentifiable priest
