### ISSUE TITLE
Add. 18,817, foll. 137–154, lower text | https://bl.syriac.uk/ms/1449

### ISSUE THREAD

**Issue by sbirol** [srophe/britishLibrary-data#1630]

**Comment by wlpotter** [comment]
Thanks @sbirol -- were there questions on this one? I see you marked as 'done' on the spreadsheet; there's no need to create a GitHub issue if there are no problems to address with the manuscript.

As long as the file is saved, changes are commited to GitHub, and then pushed to the online version, we will be able to see and review them

**Comment by sbirol** [comment]
Thanks for the answer @wlpotter . I was unsure whether you would receive a notification without clicking on ‘create issues’. Other than that, no questions, everything is fine.
