### ISSUE TITLE
Add. 12,145, lower text | https://bl.syriac.uk/ms/1441

### ISSUE THREAD

**Issue by PGAMiller** [srophe/britishLibrary-data#1632]
The lower text has only an implied date. There is an existing comment asking if there is a better way to clarify the time other than "notAfter = 0925", in p2handNote1.

XPath: /TEI/teiHeader/fileDesc/sourceDesc/msDesc/msPart/history/origin/origDate

**Comment by wlpotter** [comment]
Thanks @PGAMiller, since the inference about it being before the 10th c. comes from how Wright dates the upper text, we can just leave as-is in the origDate. You could, if you wanted, add to the handNote that it is likely before the 10th century based on the dating of the upper text
