### ISSUE TITLE
Add. 17,134 | https://bl.syriac.uk/ms/763 Greek (coptic) font size uneven

### ISSUE THREAD

**Issue by YaelNueKr** [srophe/britishLibrary-data#1635]
### Problems with Manuscript Contents

The font of the greek (written in coptic script) is often uneven in the website. is there a way of fixing this?

**Comment by wlpotter** [comment]
Yes, @YaelNueKr this is caused by there being mixed-language content in the rubric element. If you tag the Coptic portions with `<foreign xml:lang="cop"></foreign>`, then this will fix the display (once we publish the updated records)
