### ISSUE TITLE
unclear page numbers: these potentially ref to page nos. in Opera t.ii. How best to mark them?

### ISSUE THREAD

**Issue by mts272** [srophe/britishLibrary-data#1637]
https://github.com/srophe/britishLibrary-data/blob/7ed9d834c099761265cdcb643468a8d01e06be53/data/tei/337.xml#L629

**Comment by davidamichelson** [comment]
@mts272 Maria, thank you for this. In this case it looks like these page numbers do refer to the earlier bibl (mentioned as Opera t.ii in line [608](https://github.com/srophe/britishLibrary-data/blob/7ed9d834c099761265cdcb643468a8d01e06be53/data/tei/337.xml#L608)). Please just assign the same local URI to all of these bibls that are the same text.

```
<note>See <bibl>Opera, t. ii., p. 158<ref target="smblBibl52"/></bibl>.</note>
...
<note>These extracts comprise <bibl>pp. 169 D—171 D<ref target="smblBibl52"/></bibl>, and <bibl>pp. 172 B —173 D<ref target="smblBibl52"/></bibl>.</note>
```

**Comment by mts272** [comment]
Got it! Thanks!
