### ISSUE TITLE
Add. 14,609 | {https://bl.syriac.uk/ms/347URI}

### ISSUE THREAD

**Issue by GiovanniGomiero** [srophe/britishLibrary-data#1642]
### Problems with Manuscript Contents

The manuscript has been corrected. But there is an evident mistake in the catalogue, the section _Excerpts from the Paradise of the Fathers of Palladius_ is misleading: first, a manuscript of 6th c. of the Paradise of the Fathers is anachronistic; second, this section is clearly the _Historia Monachorum in Aegypto_, attributed to Jerom in the Syriac tradition (version R2 in the analysis by Tóth 2010). Is it possible to modify/integrate the title of Wright with the correct attribution to Pseudo-Jerome, and with the correct title _Historia Monachorum in Aegypto_?

**Comment by davidamichelson** [comment]
@GiovanniGomiero Thanks for this. While these sorts of updates need to be made to Wright, for now we are just encoding what Wright records. I have tagged this record with "Correction to Wright" and so in a future revision a note could be added. Please close this issue after your read this reply.
