### ISSUE TITLE
Add. 17,232 | https://bl.syriac.uk/ms/1015 Place record question 

### ISSUE THREAD

**Issue by bogdg** [srophe/britishLibrary-data#1649]
Uncertain whether "Egypt" needs a place record

**Comment by wlpotter** [comment]
@bogdg in this case, where it is part of the personal name, we would not mark Egypt as a placeName. It does look, though, like we'd want to update to include the full personal name in the persName element:

```
<persName>John (VI., bar Abū Ghālib)</persName> patriarch of
                      <placeName>Egypt</placeName>
```

should become

```
<persName>John (VI., bar Abū Ghālib) patriarch of Egypt</persName>
```
