### ISSUE TITLE
Add. 12,174 | https://bl.syriac.uk/ms/70 – definition of "sect"

### ISSUE THREAD

**Issue by nunziadirienzo** [srophe/britishLibrary-data#1669]
Should we somehow comment when Wrights says: Life of Jacob Baradaeus, bishop of Edessa, from whom the SECT of the Jacobites took its name (p. 1131)? Or we just suppose that "sect" can be used without a negative meaning?

**Comment by davidamichelson** [comment]
Thanks, in scholarly usage this is not necessarily negative, so I don't think this needs marking.

**Comment by davidamichelson** [comment]
Please close after reading.
