### ISSUE TITLE
Add. 14,668, foll. 37–39 | https://bl.syriac.uk/ms/491 missing decoNote

### ISSUE THREAD

**Issue by wlpotter** [srophe/britishLibrary-data#1690]
@SPuchkova a scholar who is using the SMBL database while working in the British Library emailed us this error. I see you are assigned to work on this file, so I wanted to flag it for you:

In https://bl.syriac.uk/ms/491 for Add. 14,668, foll. 37–39, Wright describes a cross on fol. 37a that appears to be missing from the description. It should be added as a `decoNote` (`physDesc/decoDesc/decoNote`). The `@type` on the decoNote should be "illustration", I believe.

You can use these lines of code as a model: https://github.com/srophe/britishLibrary-data/blob/main/data/tei/143.xml#L199-L204

Let me know if you have any questions, thanks!

**Comment by SPuchkova** [comment]
Okay, got it.

**Comment by SPuchkova** [comment]
Resolved it

**Comment by SPuchkova** [comment]
Done
