### ISSUE TITLE
Add. 12,178 | https://bl.syriac.uk/ms/10 Bibl question

### ISSUE THREAD

**Issue by bogdg** [srophe/britishLibrary-data#1697]
Following up in the same area (lines 500ff), the folio no is tagged as bibl, just wanted to double check whether or not it should not be marked as bibl.

https://github.com/srophe/britishLibrary-data/blob/7ed9d834c099761265cdcb643468a8d01e06be53/data/tei/10.xml#L581

**Comment by wlpotter** [comment]
I think this is the same as with #1695 where if it is an excerpt from the manuscript, tag it as a quote element instead
