### ISSUE TITLE
Add. 12,178 | https://bl.syriac.uk/ms/10 Tagging placeName question

### ISSUE THREAD

**Issue by bogdg** [srophe/britishLibrary-data#1698]
I am not sure whether here it should be < placeName > Mar Mari near Seleucia </placeName> or < placeName > Mar Mari </ placeName > near < placeName > Seleucia </ placeName>

https://github.com/srophe/britishLibrary-data/blob/7ed9d834c099761265cdcb643468a8d01e06be53/data/tei/10.xml#L595
https://github.com/srophe/britishLibrary-data/blob/7ed9d834c099761265cdcb643468a8d01e06be53/data/tei/10.xml#L596

https://archive.org/details/catalogueofsyria01brituoft/page/104/mode/2up?view=theater

**Comment by davidamichelson** [comment]
@bogdg thanks for this, please mark this as two separate places and then close this issue when complete.
