### ISSUE TITLE
Arabic Displaying Out of Order Add. 17,245 | https://bl.syriac.uk/ms/1034

### ISSUE THREAD

**Issue by RachelEdney** [srophe/britishLibrary-data#1699]
The Arabic text is displaying correctly in Oxygen, but not on the website. 

Beginning here: https://github.com/srophe/britishLibrary-data/blob/7ed9d834c099761265cdcb643468a8d01e06be53/data/tei/1034.xml#L237

Website: https://bl.syriac.uk/ms/1034

**Comment by wlpotter** [comment]
Thanks @RachelEdney ! This looks to be a case where Wright has "sic" in the Arabic, so you can ignore the ordering error for now. @davidamichelson and I will work on this
