### ISSUE TITLE
Add. 17,265, foll. 2–105 | https://bl.syriac.uk/ms/1424 Not sure whether rubric or final rubric

### ISSUE THREAD

**Issue by bogdg** [srophe/britishLibrary-data#1700]
There is an Arabic annotation following the Syriac rubric and I'm not sure how to tag it since it does not seem to have been included by the previous encoders

![image](https://github.com/srophe/britishLibrary-data/assets/171574893/730f6a9e-895f-4d06-9ba3-81bc3519be82)

<img width="361" alt="image" src="https://github.com/srophe/britishLibrary-data/assets/171574893/15d137cf-812c-4e26-b72b-d56f617736b3">

https://archive.org/details/catalogueofsyria03brituoft/page/1140/mode/2up?view=theater

**Comment by wlpotter** [comment]
Thanks @bogdg we will assign someone to input the Arabic

**Comment by bogdg** [comment]
Sorry, just to clarify, I added the Arabic, but wasn't sure how to mark it.

![image](https://github.com/srophe/britishLibrary-data/assets/171574893/863cb382-55c0-45c1-85df-a91e67994166)

**Comment by wlpotter** [comment]
Ah, sorry I misunderstood. I believe having it as a finalRubric makes sense here, since كملت is often used as an equivalent to ܫܠܡܬ. The one thing I'd add is to put the locus element for f. 74 a in the Arabic finalRubric as well, since I think Wright implies that it is also on that folio?
