### ISSUE TITLE
Add. 17,266, foll. 1–50 | https://bl.syriac.uk/ms/1083 PersName tagging

### ISSUE THREAD

**Issue by bogdg** [srophe/britishLibrary-data#1709]
This is minor, but I was unsure whether to keep the original tagging of Thomas the son of Samuel:

https://github.com/srophe/britishLibrary-data/blob/7ed9d834c099761265cdcb643468a8d01e06be53/data/tei/1082.xml#L231

https://archive.org/details/catalogueofsyria02brituoft/page/864/mode/2up

**Comment by davidamichelson** [comment]
@bogdg This is similar to the other issue about nested places. While normally we do not allow nested names and places, when they occur in additions we do. Please make temporary URIs for both of these.
