### ISSUE TITLE
Add. 17,136, foll. 117, 126, lower text | https://bl.syriac.uk/ms/1541

### ISSUE THREAD

**Issue by nataliasmelova** [srophe/britishLibrary-data#1715]
Hi @wlpotter, I am just double-checking if https://syriaca.org/work/9641 covers the **Greek** text of John? Thanks.

**Comment by wlpotter** [comment]
Yes, it should -- Syriaca uses the term "literary tradition" to refer to the broader conceptual 'work' that may have versions/expressions in various languages, so this would include the Greek.
