### ISSUE TITLE
Add. 14,498 | https://bl.syriac.uk/ms/188 Author tag needed?

### ISSUE THREAD

**Issue by bogdg** [srophe/britishLibrary-data#1718]
This is probably silly but wanted to double check whether here I should add an author tag for Dioscorus?

                   </msItem>
                  <msItem xml:id="p1c2" n="21">
                    <locus from="218" to="221"/>
                    <title xml:lang="en">Fragments of the history of
                    Dioscorus of Alexandria
                    </title>
                  </msItem>

https://archive.org/details/catalogueofsyria03brituoft/page/1142/mode/2up?view=theater

**Comment by bogdg** [comment]
Likewise here (l. 400ff)

< msItem xml:id="p1b18" n="22" >
                  < locus from="222a" />
                  < title xml:lang="en">A fragment from the history of Abbā Shanudīn or Shanūdī
                  (Sanutius)
                  < /title >
                  < rubric xml:lang="syr" >ܐܒ̇ܐ ܫܲܢܘܕܝܢ < foreign xml:lang="en" >(or < foreign xml:lang="syr" >ܐܒ̇ܐ ܫܲܢܘܕܝ< /foreign >)< /foreign >
                  < /rubric >

**Comment by wlpotter** [comment]
@bogdg I believe these are hagiographic accounts about Dioscorus and others, in which case we would not mark them as authors
