### ISSUE TITLE
Add. 17,231 | https://bl.syriac.uk/ms/1014 Title missing

### ISSUE THREAD

**Issue by bogdg** [srophe/britishLibrary-data#1723]
Here (l. 168ff) the title in English is not given so the encoder used "Arranged according to the eight tones" as the title. Would it be okay to emend the title as "Chants/Antiphons of the Mother of God, etc." or something similar and mark "Arranged..." as a note?

              < msItem xml:id="b12" n="13" defective="true" >
                < locus from="34a" to="71" >Foll. 34a-71< /locus >
                < title xml:lang="en" >Arranged according to the eight tones.< /title >
                < rubric xml:lang="syr" >ܡ̈ܥܢܝܬܐ ܕܝ̇ܠܕܬ݀ ܐܠܗܐ: ܘܕܣ̈ܗܕܐ: ܘܕܬܝܒܘܬܐ. ܘܕܥ̈ܢܝܕܐ:
                           ܒܬܡ̈ܢܐ ܩ̈ܝܢܬܐ ܡܢ ܩܕܡܝܐ ܠܬܡܝܢܝܐ< /rubric >

https://archive.org/details/catalogueofsyria01brituoft/page/352/mode/2up?view=theater

<img width="357" alt="image" src="https://github.com/srophe/britishLibrary-data/assets/171574893/58d4dc33-d058-4acd-8196-5c9d2b18d1f9">

**Comment by wlpotter** [comment]
Yes, I think moving "arranged according to the eight tones" to a note is fine. For the title, I believe our convention has been to use "Part " and then the outline number/letter from Wright, so here it would be "Part l" (the lowercase letter 'L')
