### ISSUE TITLE
Add. 17,239, foll. 16–60 | https://bl.syriac.uk/ms/1026 Change addition item into msitem

### ISSUE THREAD

**Issue by bogdg** [srophe/britishLibrary-data#1724]
Should this constitute a msitem rather than an item in the additions?

https://github.com/srophe/britishLibrary-data/blob/7ed9d834c099761265cdcb643468a8d01e06be53/data/tei/1024.xml#L371

https://archive.org/details/catalogueofsyria01brituoft/page/314/mode/2up?view=theater

<img width="591" alt="image" src="https://github.com/srophe/britishLibrary-data/assets/171574893/f23d582b-d036-403f-a202-f55ccb51c1ea">

**Comment by wlpotter** [comment]
Great catch @bogdg! Yes, please make this into an msItem. It can be the last top-level item in the msContents. We would want to have the following:

- an msItem for the madrashe that includes a note saying that it is "In a modern hand"
- a handNote stating that the madrashe on f. 60 are in a modern hand (see below for what this can look like)
- keep the addition item as-is

Although a bit redundant, we do want to capture that it is both an msItem and was added later as an addition, so we need to reference it in both places.

Here's what the handNote could look like:

```
<handNote xml:id="p2handNote4" medium="unknown" scope="minor" script="syr">
    The madrāshē on fol. 60 are in a modern hand
</handNote>
```
