### ISSUE TITLE
Add. 12,141, fol. 149 | https://bl.syriac.uk/ms/1170 - Adding arabic

### ISSUE THREAD

**Issue by PGAMiller** [srophe/britishLibrary-data#1727]
This line needs Arabic added from Wright:

https://github.com/srophe/britishLibrary-data/blob/7ed9d834c099761265cdcb643468a8d01e06be53/data/tei/13.xml#L595

Arabic can be found on this page: https://archive.org/details/catalogueofsyria01brituoft/page/64/mode/1up

Parent xml file is 13.xml

**Comment by wlpotter** [comment]
Thanks @PGAMiller ! I'll mark this as needing Arabic

**Comment by Erfan-Syriaca** [comment]
Proofread. Arabic was added.
