### ISSUE TITLE
Listing of Items - Add. 14,611 | https://bl.syriac.uk/ms/349

### ISSUE THREAD

**Issue by edwards9d** [srophe/britishLibrary-data#1734]
The previous encoder of this file has chosen to make two a-level items based on Wright's not at the bottom of the right column on page 826. Because Wright mentions there was an earlier hand who mentioned these items, this is listed as a separate a-level item. My question is this. Should this be a two part document instead of two separate a-level items, or should I leave it as is? Thanks!

**Comment by wlpotter** [comment]
Thanks @edwards9d ! @davidamichelson and I will take a look

**Comment by davidamichelson** [comment]
Please close when read.
