### ISSUE TITLE
Authorship questions - Add. 12,162, foll. 1–213, 216a | https://bl.syriac.uk/ms/1426

### ISSUE THREAD

**Issue by edwards9d** [srophe/britishLibrary-data#1736]
Wright has attributed multiple works in this entry to Macarius the Great (https://syriaca.org/person/856). The previous encoder provided the syriaca.org reference for Pseudo-Macarius (https://syriaca.org/person/3501). This is likely correct (I work on this corpus, and most of the Syriac texts belong to this latter author). However, I'm wondering if we should be correcting Wright in this way? Would it be better to mark the author as Macarius the Great instead?

**Comment by wlpotter** [comment]
Thanks @edwards9d -- Dave and I will confer on this

**Comment by wlpotter** [comment]
@edwards9d this is how we would encode the authorship here:

```
<author ref="http://syriaca.org/person/856" role="https://syriaca.org/documentation/author-editor-roles.xml#incorrectly-attributed" resp="https://bl.syriac.uk/documentation/editors.xml#wwright">
  <persName xml:lang="en">Macarius the Great</persName>
</author>
<author ref="http://syriaca.org/person/3501" resp="https://bl.syriac.uk">
  <persName xml:lang="en">Pseudo-Macarius</persName>
</author>
```

A few notes on what's being asserted here:
- The first author is given the role "incorrectly-attributed", and the resp for Wright. This is saying that Wright attributes the authorship of these items to Macarius the Great (person 856), and that the SMBL editors believe this to be an incorrect attribution.
- The second author is not given the resp for the SMBL project, which is a way to say that the editorial team as a whole are making the authorship assertion that this is Pseudo-Macarius (person 3501)

[part 1 of 363.xml](https://bl.syriac.uk/ms/363#msPart1) under item 52 (p1a12), on f. 56b, has a similar example of disputed authorship to compare
