### ISSUE TITLE
Add. 14629 | https://bl.syriac.uk/ms/372 graphics

### ISSUE THREAD

**Issue by YaelNueKr** [srophe/britishLibrary-data#1750]
### Problems with Manuscript Contents

<img width="576" alt="Screenshot 2024-07-05 at 17 43 28" src="https://github.com/srophe/britishLibrary-data/assets/171554214/f4c7ddb8-fc63-475d-a1d8-d3c7b7c42a4a">

**Comment by YaelNueKr** [comment]
![Uploading Screenshot 2024-07-05 at 17.44.44.png…]()
This too

**Comment by wlpotter** [comment]
reopening so we can remember to resolve this
