### ISSUE TITLE
Arabic needs checked - Add. 17,138, foll. 1–34, 41–51, lower text | https://bl.syriac.uk/ms/1548

### ISSUE THREAD

**Issue by edwards9d** [srophe/britishLibrary-data#1759]
I am unable to proofread the Arabic in this file (lines 286-299). I've made an XML comment at the place where this needs checked. Thanks!

**Comment by Erfan-Syriaca** [comment]
Proofread. The Arabic is fine, but the folio numbers that come before each Arabic sentence are not displayed on the website.
