### ISSUE TITLE
Add. 17,149 | https://bl.syriac.uk/ms/778 - Addition of Arabic

### ISSUE THREAD

**Issue by PGAMiller** [srophe/britishLibrary-data#1782]
https://github.com/srophe/britishLibrary-data/blob/7ed9d834c099761265cdcb643468a8d01e06be53/data/tei/778.xml#L291

Arabic for Mosul needs added here.

https://archive.org/details/catalogueofsyria02brituoft/page/669/mode/1up

**Comment by Erfan-Syriaca** [comment]
Proofread. Arabic was added.
