### ISSUE TITLE
Add. 14,436, foll. 77–129 | https://bl.syriac.uk/ms/96 - Coptic and Arabic numerals need inserting

### ISSUE THREAD

**Issue by PGAMiller** [srophe/britishLibrary-data#1786]
Within the paragraph, the Arabic and Coptic numerals need inserted. Some may need images.

https://github.com/srophe/britishLibrary-data/blob/7ed9d834c099761265cdcb643468a8d01e06be53/data/tei/94.xml#L489

https://archive.org/details/catalogueofsyria01brituoft/page/126/mode/1up

**Comment by Erfan-Syriaca** [comment]
Proofread. Arabic words were added.
