### ISSUE TITLE
Add. 17,128, fol. 90 | https://bl.syriac.uk/ms/977 - Arabic Needed

### ISSUE THREAD

**Issue by PGAMiller** [srophe/britishLibrary-data#1791]
Arabic needed in p21addition1

https://github.com/srophe/britishLibrary-data/blob/7ed9d834c099761265cdcb643468a8d01e06be53/data/tei/956.xml#L2433

https://archive.org/details/catalogueofsyria01brituoft/page/100/mode/2up

**Comment by Erfan-Syriaca** [comment]
Proofread. Arabic name was added.
