### ISSUE TITLE
Add. 18,295 | https://bl.syriac.uk/ms/1113 Historical reconstruction question

### ISSUE THREAD

**Issue by bogdg** [srophe/britishLibrary-data#1797]
This is just aminir point but I came across this change note and I am not sure where it comes from as it doesn't seem to be noted in Wright, though I might be missing something

"One or more ms Parts need to be encoded into an historical reconstruction of a no longer extant manuscript."

https://github.com/srophe/britishLibrary-data/blob/7ed9d834c099761265cdcb643468a8d01e06be53/data/tei/1113.xml#L460

https://archive.org/details/catalogueofsyria03brituoft/page/1184/mode/2up

**Comment by wlpotter** [comment]
Thanks @bogdg I think this might be a case where the template the initial encoder used had all the available planned changes, and they did not remove the ones that were not applicable for this ms. Could you delete any planned change elements that don't apply to this record? I see, for example, "table", "uri", "Arabic", etc. which may also not be needed in this file
