### ISSUE TITLE
Problem with Syriac in Brackets Add. 14,714 | https://bl.syriac.uk/ms/586

### ISSUE THREAD

**Issue by RachelEdney** [srophe/britishLibrary-data#1798]
Since this Syriac quote begins with a bracketed letter, it's messing up the Syriac display and I can't figure out how to fix it. 

https://archive.org/details/catalogueofsyria01brituoft/page/346/mode/2up

https://github.com/srophe/britishLibrary-data/blob/7ed9d834c099761265cdcb643468a8d01e06be53/data/tei/586.xml#L274

**Comment by wlpotter** [comment]
This is like the 'sic' ones, so you can ignore for now and we'll take care of it

**Comment by wlpotter** [comment]
Note to self: closing this issue since we will do a systematic search and fix for brackets, sic, etc. in Syriac content
