### ISSUE TITLE
Arabic beginning with parenthesis Add. 14,704 | https://bl.syriac.uk/ms/570

### ISSUE THREAD

**Issue by RachelEdney** [srophe/britishLibrary-data#1804]
Arabic quote beginning with parentheses messes up the order of the Arabic text

https://archive.org/details/catalogueofsyria01brituoft/page/312/mode/2up

https://github.com/srophe/britishLibrary-data/blob/7ed9d834c099761265cdcb643468a8d01e06be53/data/tei/570.xml#L213

**Comment by wlpotter** [comment]
Thanks @RachelEdney this probably falls into the same category as the use of 'sic', etc., so we can take a look at it

**Comment by wlpotter** [comment]
Closing this since we will do a systematic review of these cases
