### ISSUE TITLE
Author names - Add. 17,207 | https://bl.syriac.uk/ms/869

### ISSUE THREAD

**Issue by edwards9d** [srophe/britishLibrary-data#1805]
In some of the items in this xml file, someone is mentioned as the author of some or one of the items, but Wright doesn't enumerate them further. So, for instance, in msItem b2 the item is titled "Prosphorici" and Jacob is said to be the author of one of these items. Should I list him as the author? I'm concerned that it will seem like the file is saying he is the author of all of them.

Thanks!

**Comment by davidamichelson** [comment]
@wlpotter I think in this particular case (i.e. just item b2, listing Jacob as author is okay given the limited information from Wright), the wording of the title is such that someone will need to research the multiple items here and separate them in the future but for now we would want Jacob to show up as one of the authors of this item. What do you think?

**Comment by wlpotter** [comment]
Yes, I agree with this. We can keep the author just at the more specific level in this case
