### ISSUE TITLE
Add. 17,217, foll. 37, 38 | https://bl.syriac.uk/ms/933 URI is needed for the MS outside Wright's Catalog

### ISSUE THREAD

**Issue by SPuchkova** [srophe/britishLibrary-data#1811]
URI is needed for the MS outside Wright's Catalog:
https://github.com/srophe/britishLibrary-data/blob/7ed9d834c099761265cdcb643468a8d01e06be53/data/tei/929.xml#L624

**Comment by wlpotter** [comment]
Thanks @SPuchkova, since we don't have these URIs yet, it is sufficient to have the bibl with a `@type` of "MS", as it is here. Eventually we can find all of these cases and add the URIs once they are created. But for now, it is fine to leave as it is

**Comment by SPuchkova** [comment]
Done!

**Comment by SPuchkova** [comment]
@type with 'MS' as value is added
