### ISSUE TITLE
Add. 14,688 | https://bl.syriac.uk/ms/546 Arabic and Coptic needed

### ISSUE THREAD

**Issue by SPuchkova** [srophe/britishLibrary-data#1825]
Coptic is needed here:
https://github.com/srophe/britishLibrary-data/blob/7ed9d834c099761265cdcb643468a8d01e06be53/data/tei/546.xml#L444 
and around that place.

Arabic is needed in the note at the end of the file that I encoded myself because it was absent. I left a comment around the place where it is needed.

**Comment by Erfan-Syriaca** [comment]
Proofread. 
Arabic was added.
