### ISSUE TITLE
Add. 14,735, foll. 24–50 | https://bl.syriac.uk/ms/649 PlaceName question

### ISSUE THREAD

**Issue by bogdg** [srophe/britishLibrary-data#1833]
Just wanted to double check whether "the Egyptian desert" would need a tag (l. 426)

![image](https://github.com/srophe/britishLibrary-data/assets/171574893/dbb7e033-16e1-443b-8bc2-d6eba8ae270d)

https://archive.org/details/catalogueofsyria03brituoft/page/1148/mode/2up?view=theater

**Comment by wlpotter** [comment]
Yes, we can have a place name for the Egyptian desert as a region. I believe we would use the URI http://syriaca.org/place/289 (for the Scetis region) here
