### ISSUE TITLE
Add. 14,735, foll. 72–173 | https://bl.syriac.uk/ms/651 Decoration question

### ISSUE THREAD

**Issue by bogdg** [srophe/britishLibrary-data#1834]
Apologies but I wanted to clarify something about a decoration note. Wright notes:
<img width="339" alt="image" src="https://github.com/user-attachments/assets/28cf7fe3-b83b-4450-b05c-f853a633cb15">

But this is not described as such in tei. The only reference is:
![image](https://github.com/user-attachments/assets/250f432c-2f65-4966-90ea-67491d7ea5aa)

Is that okay or should I add more information as in Wright?

https://archive.org/details/catalogueofsyria03brituoft/page/1122/mode/2up?view=theater

**Comment by wlpotter** [comment]
Thanks @bogdg , yes, please do add this info from Wright. I don't think it ended up in another part of the file, and we would want to include it in this decoNote
