### ISSUE TITLE
Add. 14,681 | https://bl.syriac.uk/ms/537 Coptic and Arabic is needed to be added

### ISSUE THREAD

**Issue by SPuchkova** [srophe/britishLibrary-data#1844]
There is one special Coptic character, which I don't have on my keyboard, and an Arabic word are missing:
https://github.com/srophe/britishLibrary-data/blob/7ed9d834c099761265cdcb643468a8d01e06be53/data/tei/537.xml#L262
https://github.com/srophe/britishLibrary-data/blob/7ed9d834c099761265cdcb643468a8d01e06be53/data/tei/537.xml#L269
See here:
https://archive.org/details/catalogueofsyria01brituoft/page/79/mode/1up

**Comment by Erfan-Syriaca** [comment]
Proofread. The Arabic word was added.
