### ISSUE TITLE
Add. 14,541, foll. 39–49 | https://bl.syriac.uk/ms/270 Clarification on addition

### ISSUE THREAD

**Issue by bogdg** [srophe/britishLibrary-data#1888]
I added the marginal Greek notes to the relevant sections since if they're only left as a separate item they lack context, but I wanted to ask whether they should be listed in an addition as well as they have been written by a previous encoder. I assume having them twice isn't a problem?

<img width="394" alt="image" src="https://github.com/user-attachments/assets/eb800819-0f76-496b-ab9c-f5031e8f8bc9">

<img width="757" alt="image" src="https://github.com/user-attachments/assets/34d282f5-4245-401c-b047-a8143d8ade59">

<img width="414" alt="image" src="https://github.com/user-attachments/assets/f0c67c7c-f989-4b4e-b9a3-cd73c7c5e87e">

![image](https://github.com/user-attachments/assets/4b9c500e-2a6c-408c-9ea8-fed248a7973a)

**Comment by wlpotter** [comment]
Thanks @bogdg , I think it is fine to have these in both places. I think we would want to add to the addition 2 an indication that these are not all of the Greek marginally, maybe something like "...many words written in Greek letters, of which the following are specimens"
