### ISSUE TITLE
Syriaca URIs, including mss, should all be http not https

### ISSUE THREAD

**Issue by wlpotter** [srophe/britishLibrary-data#21]
There is likely inconsistency, and most of our legacy data still has http (and I think the post-processing script is also using http rather than https)

**Comment by davidamichelson** [comment]
Yes, we should follow the example of GEDSH and BQG and encode both the project and the Syriaca.org URIs.

**Comment by davidamichelson** [comment]
We can place both uri inside `@target` separated by whitespace

**Comment by wlpotter** [comment]
Updated the Syriaca addresses and URIs t be 'http' rather than 'https'. I'm moving discussion of tei:bibl references to other BL mss to #44, see especially [this comment](https://github.com/srophe/britishLibrary-data/issues/44#issuecomment-1192643168)
