### ISSUE TITLE
Move encoding of Wright taxonomy keywords to a tei:head/tei:listRelation/tei:relation element

### ISSUE THREAD

**Issue by wlpotter** [srophe/britishLibrary-data#22]
The note on the TEI Guideline's for [tei:keywords](https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-keywords.html) states:

>Each individual keyword (including compound subject headings) should be supplied as a [term](https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-term.html) element directly within the [keywords](https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-keywords.html) element. An alternative usage, in which each [term](https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-term.html) appears within an [item](https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-item.html) inside a [list](https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-list.html) is permitted for backwards compatibility, but is deprecated.

We currently encode Wright's taxonomic headings similar to this deprecated method (example from record [317](https://github.com/srophe/wright-catalogue/blob/master/data/5_finalized/317.xml#L457-L465):

```
      <textClass>
        <keywords scheme="#Wright-BL-Taxonomy">
          <list>
            <item>
              <ref target="#theo-collected"/>
            </item>
          </list>
        </keywords>
      </textClass>
```

[tei:term](https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-term.html) can take `@ref` attributes (cf. [this Guidelines example](https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-term.html#index-egXML-d52e31472)), so we may want to consider updating our encoding to this style:

```
      <textClass>
        <keywords scheme="#Wright-BL-Taxonomy">
          <term ref="#theo-collected">Collected Authors</term>
        </keywords>
      </textClass>
```
(N.B. the text node of the tei:term element comes from the corresponding tei:catDesc text node (`/TEI/teiHeader/encodingDesc/classDecl/taxonomy/category/category/catDesc[@xml:id="theo-collected"]`)

This should be an easy update to automate by script.

----

An alternative proposal to consider would be to move the data from Wright's taxonomy to a [tei:classCode](https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-classCode.html) or [tei:catRef](https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-catRef.html). We use the latter, I believe, for Caesarea Testimonia.

**Comment by wlpotter** [comment]
@davidamichelson we should revisit this as having a summary is pretty important to us. We had discussed using the top-level `msItem/title` in cases where we have less than 5 (or some other standard number). In larger cases we would use the taxonomy value from Wright.

We could stick to that plan, but maybe follow e-ktobe and have a list in the tei:head (cf. #14) that contains the Wright Taxonomy value.

**Comment by davidamichelson** [comment]
Yes, let's follow the ektobe model with TEI:head

**Comment by wlpotter** [comment]
Note to self: use a list in the head with a type for Wright-BL-Schema. Each item can have a tei:ref with the existing `@target`. The text node of the ref should come from the classDecl taxonomy

**Comment by wlpotter** [comment]
I'm wondering if we want this to be a tei:list or a tei:listRelation, with each child tei:relation element connecting the ms to the taxonomy value.

I'm anticipating #64 and also thinking along the lines of #95. Here is an example of what that could look like:

```
<head>
  ...
  <listRelation type="Wright-BL-Taxonomy">
    <desc>Descriptive prose letting the user know what this list is for</desc>
    <relation name="wright-taxonomy" "ref="syriaca:hasSubject" active="https://bl-syriac-mss.uk/321" passive="#theo-single">
      <desc>Individual Authors</desc>
    </relation>
  </listRelation>
  ...
</head>
```

**Comment by wlpotter** [comment]
See #101  reopen or create new issues for edits
