### ISSUE TITLE
Credit  student proofreaders and SMBL 2024 Workshop proofreaders

### ISSUE THREAD

**Issue by wlpotter** [srophe/britishLibrary-data#261]
We will want a way to credit the students who are proofreading the records, as well as those who end up fixing the errors caught in proofreading. Probably a tei:respStmt, but need to think about how we are logging/tracking them. Most obvious would be the assignment column in the spreadsheet https://docs.google.com/spreadsheets/d/1-RmpEdDh2PjMwbDzD8TVTtyAubmHyLMGuwaikkDafaM/edit#gid=0

- need to consider cases where we reassign an ms when we switch to proofreading the contents and additions

**Comment by wlpotter** [comment]
Discuss the following:
- [x] what is the respStmt language for student proofreaders?
- [x] what is the respStmt language for SMBL 2024 workshop editors?
- [x] do we also give an editor element for the workshop editors, and if so is it type="creator"?
- [x] what to put in the revisionDesc for these?
- [x] add a section in the about or similar page that credits the workshop editors?
- [x] and make sure our list of students is up to date there

**Comment by davidamichelson** [comment]
Workshop editors will take role="review-editor"?
Students receive a resp statement for proofreading

**Comment by davidamichelson** [comment]
Yes add a section to the about page for review editors.

**Comment by davidamichelson** [comment]
and make sure our list of students is up to date:
Yes, we need to run a script across all resp stmts and across git hub users perhaps.

**Comment by wlpotter** [comment]
It looks like we duplicate names in the Contributors section of the about page, even when they are in above sections (e.g., Peter Miller is in both Contributors and Project Managers). Is this what we want for Review Editors as well?

**Comment by wlpotter** [comment]
PR #1928 adds the proofreader credit to the XML; I've also updated the about.html and editors.xml pages on the app (on the development branch)

**Comment by wlpotter** [comment]
Done
