### ISSUE TITLE
Normalize shelfmark format

### ISSUE THREAD

**Issue by wlpotter** [srophe/britishLibrary-data#51]
We have a range of formats and inconsistencies: "Add. MS XX,XXX"; "Add MS XXXXX"; etc.

Decide the preferred format, and if that should be uniform or if there should be a difference between the `tei:titleStmt/tei:title` and the `idno` for the shelfmark.

**Comment by wlpotter** [comment]
One other consideration here is allowing 'fuzzy searching' for variant formats -- so a user can still find "14,475" if they searched for "14475", for example.

**Comment by davidamichelson** [comment]
Add a variant that is not visualized in the HTML that says Add 14531 (no period, no comma) but use the period and comma as our display version.

**Comment by wlpotter** [comment]
The not displayed version should be called "Bl-Shelfmark-simplified" (needs an app issue as well)

**Comment by wlpotter** [comment]
I think the way I'll do this is to pull out the URIs and shelfmarks into a spreadsheet, clean up using OpenRefine, etc., and then update data using the URIs as the unique key. We will end up with the two versions:

- `Add. xx,xxx`: "Add. 14,613"
- `Add MS xxxxx`: "Add MS 14613"

When we add folio ranges for parts, we should have:

- `Add. xx,xxx, fol(l). x(&ndash;y)` (with the parenthetical portions being optional): "Add. 14,631, foll. 45&ndash;53"
- `Add MS xxxxx, fol(l). x(-y)`: "Add MS 14631, foll. 45-53

Finally, for palimpsests we will have:

- `Add. xx,xxx, upper text`: "Add. 14,486, upper text"
- `Add MS xxxxx, upper text`: "Add MS 14486, upper text"

And with both range and palimpsest:

- `Add. xx,xxx, fol(l). x(&ndash;y), upper text`: "Add. 14,665, foll. 1&ndash;7, upper text"
- `Add MS xxxxx, fol(l). x(-y), upper text`: "Add MS 14665, foll. 1-7, upper text"

**Comment by wlpotter** [comment]
See #102 re-open or create new issue for updates
