### ISSUE TITLE
Find and correct places in BL Data with xml:Lang="syr" that shouldn't exist or are anomalies.

### ISSUE THREAD

**Issue by davidamichelson** [srophe/britishLibrary-data#531]
See https://github.com/srophe/britishLibrary/issues/140

**Comment by wlpotter** [comment]
Here is a list of all the elements that have an `@xml:lang="syr"`:

foreign
rubric
quote
finalRubric
incipit
persName
explicit
placeName
colophon
title
origPlace
sic
reg
orig
note
corr
smblPers825

----

smblPers825 is of course an anomaly -- should likely be a persName with a `@ref` attribute...

note might be the only one that is an anomaly, though the set of sic, reg, orig, corr we will review separately

**Comment by wlpotter** [comment]
The three notes should be changed. Two should be xml:lang="en", which have quotes and foreign elements that have Syriac content and are tagged; the other should be a tei:quote instead. I'll make these changes

**Comment by wlpotter** [comment]
Done; I've left sic, corr, reg, and orig since those will be systematically reviewed and normalized separately
