### ISSUE TITLE
Should xml:lang on rubrics match the main textLang or the handNotes?

### ISSUE THREAD

**Issue by wlpotter** [srophe/britishLibrary-data#55]
A few of our encoders changed the xml:lang attributes to match the `handNote/@script` values on `tei:rubric` elements. So we ended up with, e.g., `@xml:lang="syr-Syrn"` in some cases. Do we want to normalize rubric langs to follow the more generic `tei:textLang` element or the more specific hand note information?

**Comment by davidamichelson** [comment]
Strip the data out of rubric since we can't be sure this is correct. Leave it in the handNote. A later revision can check the manuscripts visually and enter the scripts.

**Comment by wlpotter** [comment]
Note on this: probably can look at the xml:lang attributes in the msContents for the regex `-.+?"` and replace simply with `"`, as this should remove any script codes. Do some testing on this and then find and replace in files

**Comment by wlpotter** [comment]
This may be a bit more complicated. There are cases where we have Garshuni contents, such as https://bl.vuexistapps.us/manuscript/1114. I think we'd want to include the script codes for these?

If so, the following regex should be more targeted:

(find in `//msContents//*/@xml:lang`). `"syr-Syr."`

This will find cases where the Syriac writing system is used with a Syriac script code. It is only in those cases that we want to remove the script code because it is otherwise Garshuni. Note that there are no cases of Arabic with an Arabic script code, "ar-Arab", so we don't need to worry about that.

**Comment by wlpotter** [comment]
Fixed
