### ISSUE TITLE
Manuscripts needing their title fixed

### ISSUE THREAD

**Issue by PGAMiller** [srophe/britishLibrary-data#73]
Manuscript URIs 365, 530, and 1093 currently have typographical issues in their data (not capitalizing MSS, and similar minor issues)

**Comment by wlpotter** [comment]
@davidamichelson FYI I transferred this to the bl-data repo. Will check these records and fix typographical issues.

**Comment by wlpotter** [comment]
- [x] 365
- [x] 530
- [x] 1093
