### ISSUE TITLE
"Philoxenos of Mar" displaying as name

### ISSUE THREAD

**Issue by PGAMiller** [srophe/britishLibrary-data#74]
Currently in the manuscript visualization Philoxenos appears as "Philoxenos of Mar"

See this manuscript for an example: http://wwwb.library.vanderbilt.edu/exist/apps/srophe/manuscript/365

@davidamichelson

**Comment by wlpotter** [comment]
@davidamichelson transferring to the bl-data repo. We should double check the updated visualizations to see if this is still a problem. https://bl.vuexistapps.us/manuscript/365 appears to be displaying correctly as "[Philoxenus of Mabug](http://syriaca.org/person/44)". Leaving this open for further spot-checking.

**Comment by wlpotter** [comment]
Can't find any examples of "Philoxenus of Mar" in data; this should be fixed.
