### ISSUE TITLE
Items with no title or content info

### ISSUE THREAD

**Issue by nathangibson** [srophe/britishLibrary-data#76]
http://syriaca.org/manuscript/1318 has no title and no info in the catalogue about the content of the ms. 

Should I just leave the title blank and try to find something appropriate when I'm editing the work record? Or should I use a title with something like the following?
`<title type="supplied" reason="missing" resp="http://syriaca.org/documentation/editors.xml#ngibson">Title not supplied</title>`

**Comment by wlpotter** [comment]
Here's what I've found for the three BL manuscripts with missing or illegible titles:

- 1415#p2a1 needs a title with 'Unspecified contents'.
- 1416#p4a1 needs a title with 'Unspecified contents'.
- 899#p5b2 is tricky as we know it is a sub-item of "Philosophical and theological disquisitions, partly in the form of a dialogue". But this item's rubric is illegible. Do we call it 'Unspecified contents'? Or 'Part 2'? or 'Unspecified philosophical or theological disquisition'?
