### ISSUE TITLE
Distinguishing parent from child item in manuscript/99

### ISSUE THREAD

**Issue by nathangibson** [srophe/britishLibrary-data#77]
In http://wwwb.library.vanderbilt.edu/manuscript/99/tei I don't see how to distinguish the containing work in p2a1 from the text of Paul of Tella's translation in p2b2. The latter is marked as http://syriaca.org/work/174 (1 Kings (3rd) (LXX/Septuagint Version)), but I would think this would also apply to the containing work.

srophe/britishLibrary-data#75

**Comment by wlpotter** [comment]
@davidamichelson transferring to bl-data repo. I'm not sure if there's anything left here? I think maybe we need to work out where to put Paul of Tella as a translator?

**Comment by wlpotter** [comment]
I believe this is fine as it is currently (cf. https://bl.vuexistapps.us/manuscript/99). Paul of Tella is listed as the translator for item p2a1, the container item for the summary of contents and book of Kings, and p2b2, the book of Kings proper. To avoid ambiguity (especially when we serialize this as linked data), we have opted not to rely on XML inheritance rules. So, I think this correctly represents the situation where Paul of Tella is only explicitly defined as the translator of the book of Kings, and the containing item. We can't be sure if Paul of Tella added the summary of contents or if this is a scribal composition, so I think it's correct to leave item p2b1 unauthored.
