### ISSUE TITLE
msItems with no n or xml:id

### ISSUE THREAD

**Issue by nathangibson** [srophe/britishLibrary-data#78]
Should the top-level msItem in http://syriaca.org/manuscript/155 have an `@n` and `xml:id`? 

srophe/britishLibrary-data#75

**Comment by wlpotter** [comment]
@davidamichelson transferring to bl-data repo. Need to check that record 155 has the proposed changes. Though the `@n` and `@xml:id` values should be taken care of with the maintenance script, cf. #42

**Comment by wlpotter** [comment]
Title has been fixed. The issue with the xml:id and n attributes will be fixed with #42
