### ISSUE TITLE
Add a note to records whose addition items are out of order

### ISSUE THREAD

**Issue by wlpotter** [srophe/britishLibrary-data#88]
We had discussed this previously as many of the addition items are out of folio order. Sometimes this is fine as Wright described them out of order, or they make more sense out of order. But we talked about adding a (temporary) note to alert proofreaders when it is the case and ask them to check that the order we have is preferred.

This can be done by script, most likely. Can also include the note if one or more addition items don't have a child locus element. We should discuss to make sure this is still something we want to do.

**Comment by davidamichelson** [comment]
Sure if you think you can do that easily!

**Comment by wlpotter** [comment]
Note to self, I think `//additions/note` is a good place to put these. I will give it a `@type` of "proofreader-note" so we can later find and remove these easily (and it can serve as a useful target for the app to display a label)

**Comment by wlpotter** [comment]
#105 will fix this. Reopen or open a new issue if edits are needed.
